env: RAKE_TASK=spec
cache: bundler
language: ruby
matrix:
  include:
  - env: RAKE_TASK=rubocop
    rvm: '2.2'
rvm:
- '2.2'
- '2.1'
- '2.0'
- 'jruby-9'
- 'rbx-2'
script: bundle exec rake $RAKE_TASK
sudo: false
